export const FAQ_SEED = [
  { intent: "FAQ_PROCESS", question: "How does this process work?", response: "We purchase homes directly for cash. You tell us about the property, we evaluate it, and if it’s a fit we make a no-obligation cash offer. If you accept, we handle the paperwork and close on your timeline." },
  { intent: "FAQ_FEES", question: "Do I have to pay any fees or commissions?", response: "No. There are no commissions, agent fees, or hidden costs. The offer we make is the amount you receive at closing." },
  { intent: "FAQ_TRUST", question: "Is this a legitimate company or a scam?", response: "Yes, we’re a legitimate home-buying company. We use standard purchase agreements and licensed title companies to handle the closing safely and transparently." },
  { intent: "FAQ_PROCESS", question: "How fast can you close?", response: "Closings typically happen in as little as 7–14 days, but we can adjust to your preferred timeline if you need more time." },
  { intent: "FAQ_PROCESS", question: "Do you buy houses that need repairs?", response: "Yes. We buy properties as-is, so you don’t need to fix anything or clean the property before selling." },
  { intent: "FAQ_PROCESS", question: "Will you need to visit the property?", response: "In many cases we can make an offer remotely. Occasionally we may request a walkthrough or inspection to confirm details, but we work around your schedule." },
  { intent: "FAQ_PROCESS", question: "Am I obligated to accept your offer?", response: "No. Our offers are completely no-obligation. You’re free to accept, decline, or explore other options." },
  { intent: "FAQ_PROCESS", question: "How do you determine the offer price?", response: "We look at recent comparable sales, the property’s condition, and current market demand to arrive at a fair cash offer." },
  { intent: "FAQ_PROCESS", question: "What happens after I accept the offer?", response: "Once you accept, we open escrow with a licensed title company. They handle the paperwork, title search, and closing, and you get paid at closing." },
  { intent: "FAQ_PROCESS", question: "Do you pay cash?", response: "Yes. We use cash or cash-equivalent funding, so financing delays are not an issue." },
  { intent: "FAQ_PROCESS", question: "Can I choose my closing date?", response: "Yes. We work around your preferred closing timeline whenever possible." },
  { intent: "FAQ_GENERAL", question: "What if the property has tenants?", response: "That’s usually not a problem. We can often purchase tenant-occupied properties and work around existing leases." },
  { intent: "FAQ_GENERAL", question: "What if I owe money on the house?", response: "That’s fine. Any existing mortgage or liens are typically paid off at closing through the title company." },
  { intent: "FAQ_CONTRACT", question: "Can I back out after signing?", response: "Most contracts include an inspection or due-diligence period that allows you to cancel without penalty. We’ll explain the terms clearly before you sign." },
  { intent: "FAQ_TRUST", question: "Who handles the paperwork?", response: "The title company prepares and manages all legal paperwork to ensure a smooth and secure transaction." },
  { intent: "FAQ_TRUST", question: "Will my information be shared or sold?", response: "No. Your information is only used to evaluate your property and complete the transaction if you move forward." },
  { intent: "FAQ_PROCESS", question: "Do you buy inherited or probate properties?", response: "Yes. We frequently work with inherited and probate properties and can help guide you through the process." },
  { intent: "FAQ_PROCESS", question: "Why should I sell this way instead of listing?", response: "Selling directly avoids showings, repairs, agent commissions, and long timelines. It’s designed for speed, convenience, and certainty." },
  { intent: "OBJECTION_PRICE", question: "Your offer is too low", response: "I understand — and that’s completely fair. We base our offers on recent sales and repair needs. If there’s flexibility, what number would feel fair for you so we can see if we can bridge the gap?" },
  { intent: "OBJECTION_DELAY", question: "I need to think about it", response: "Of course — this is a big decision. If it helps, we can hold the offer for a few days and answer any questions. What would be a good time to check back in?" },
]
